### ISSUE TITLE
请问怎么异步加载组件？

### ISSUE THREAD

**Issue by SyanH** [kianfang/vue-import#1]
感谢作者这个项目，很好用，只不过现在遇到个问题，菜单想动态加载，然后想实现懒加载的效果，不知如何处理，请指点！

**Comment by kianfang** [comment]
试试`Vue Router`的[动态路由](https://router.vuejs.org/guide/advanced/dynamic-routing.html)，监听菜单点击事件，然后通过
新增路由配置达到动态加载的效果（新增前可以检查下是否已存在路由配置）：
```js
router.addRoute({ path: '/some/path', component: await vueImport('./some/component.vue') })
```
如果新增后页面没有更新，可以再尝试手动触发路由渲染：
```js
router.replace(router.currentRoute.value.fullPath)
```

**Comment by SyanH** [comment]
好的，我试下，感谢！

**Comment by kianfang** [comment]
另外，Vue支持定义[异步组件](https://vuejs.org/guide/components/async.html)，也是一种比较好的实现方式：
```js
import { defineAsyncComponent } from 'vue';

// 路由配置
const routes = [{
  path: '/some/path', 
  component: defineAsyncComponent(() => vueImport('./some/component.vue'))
}]
```

**Comment by SyanH** [comment]
嗯嗯，好的，这样就不用一开始加载一堆组件了，谢谢解惑
