### ISSUE TITLE
import JS on component

### ISSUE THREAD

**Issue by pipiscrew** [kianfang/vue-import#3]
Hi, 

on the example you have on repo, I cannot import a javascript file on component 
( component/home.vue ). 

`component/home.vue` in detail : 
```js
<script>
import general from '../general.js';

export default {
  data() {
    return {
      title: 'Home',
    }
  },
}
</script>
```

the error is 
> Uncaught TypeError: Failed to resolve module specifier "../general.js". Invalid relative url or base scheme isn't hierarchical.

even I use **./general.js** and add the file **near** the component still is not resolved.. 

any solution ?

[edit]
the same happens with you would like to import a **vue sub component** as 
```js
import CountriesDetail from './CountriesDetail.vue'; 
```

**Comment by kianfang** [comment]
`v0.2.1` has been released and now supports relative url import.

### PR
https://github.com/kianfang/vue-import/pull/4

### Example
https://unpkg.com/vue-import@0.2.1/example/index.html
<img width="1002" alt="image" src="https://github.com/kianfang/vue-import/assets/16569491/772b9d4d-7cdc-4b42-bada-23369128049e">

**Comment by pipiscrew** [comment]
see 
https://github.com/pipiscrew/DBManager


![2023-11-25_002734](https://github.com/kianfang/vue-import/assets/3852762/fc69d159-f005-41ed-b098-6be17098f18c)

**Comment by pipiscrew** [comment]
@kianfang v2.4.4.8 fixes some nasty issues
